{% set version = "1.0.3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-origami
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/origami_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/origami/origami_{{ version }}.tar.gz
  sha256: 43d33c47d66a08f84cb4914497a5ebea9dd0937151f47f41c3947e4a6d4b900c

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-abind
    - r-data.table
    - r-future
    - r-future.apply
    - r-listenv
  run:
    - r-base
    - r-abind
    - r-data.table
    - r-future
    - r-future.apply
    - r-listenv

test:
  commands:
    - $R -e "library('origami')"           # [not win]
    - "\"%R%\" -e \"library('origami')\""  # [win]

about:
  home: https://tlverse.org/origami
  license: GPL-3
  summary: A general framework for the application of cross-validation schemes to particular
    functions. By allowing arbitrary lists of results, origami accommodates a range
    of cross-validation applications.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: origami
# Title: Generalized Framework for Cross-Validation
# Version: 1.0.1
# Authors@R: c( person("Jeremy", "Coyle", email = "jeremyrcoyle@gmail.com", role = c("aut", "cre", "cph"), comment = c(ORCID = "0000-0002-9874-6649")), person("Nima", "Hejazi", email = "nh@nimahejazi.org", role = "aut", comment = c(ORCID = "0000-0002-7127-2789")), person("Ivana", "Malenica", email = "imalenica@berkeley.edu", role = "ctb", comment = c(ORCID = "0000-0002-7404-8088")) )
# Maintainer: Jeremy Coyle <jeremyrcoyle@gmail.com>
# Description: A general framework for the application of cross-validation schemes to particular functions. By allowing arbitrary lists of results, origami accommodates a range of cross-validation applications.
# Depends: R (>= 3.0.0),
# License: GPL-3
# URL: https://tlverse.org/origami
# BugReports: https://github.com/tlverse/origami/issues
# Encoding: UTF-8
# Imports: abind, methods, data.table, future, future.apply, listenv
# Suggests: testthat, class, rmarkdown, knitr, stringr, forecast, randomForest
# LazyData: true
# VignetteBuilder: knitr
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2019-05-01 17:46:59 UTC; jrcoyle
# Author: Jeremy Coyle [aut, cre, cph] (<https://orcid.org/0000-0002-9874-6649>), Nima Hejazi [aut] (<https://orcid.org/0000-0002-7127-2789>), Ivana Malenica [ctb] (<https://orcid.org/0000-0002-7404-8088>)
# Repository: CRAN
# Date/Publication: 2019-05-01 21:50:03 UTC
