{% set version = "1.0.5" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-origami
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/origami_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/origami/origami_{{ version }}.tar.gz
  sha256: 8d0d08aaecc428cbbf5db4615ad3623777c10c6d7947a1cc3ccc7f8db8cb5263

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-abind
    - r-assertthat
    - r-data.table
    - r-future
    - r-future.apply
    - r-listenv
  run:
    - r-base
    - r-abind
    - r-assertthat
    - r-data.table
    - r-future
    - r-future.apply
    - r-listenv

test:
  commands:
    - $R -e "library('origami')"           # [not win]
    - "\"%R%\" -e \"library('origami')\""  # [win]

about:
  home: https://tlverse.org/origami
  license: GPL-3.0-only
  summary: A general framework for the application of cross-validation schemes to particular functions. By allowing arbitrary lists of results, origami accommodates a range of cross-validation applications.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: origami
# Title: Generalized Framework for Cross-Validation
# Version: 1.0.3
# Authors@R: c( person("Jeremy", "Coyle", email = "jeremyrcoyle@gmail.com", role = c("aut", "cre", "cph"), comment = c(ORCID = "0000-0002-9874-6649")), person("Nima", "Hejazi", email = "nh@nimahejazi.org", role = "aut", comment = c(ORCID = "0000-0002-7127-2789")), person("Ivana", "Malenica", email = "imalenica@berkeley.edu", role = "ctb", comment = c(ORCID = "0000-0002-7404-8088")), person("Rachael", "Phillips", email = "rachaelvphillips@berkeley.edu", role = "ctb", comment = c(ORCID = "0000-0002-8474-591X")) )
# Maintainer: Jeremy Coyle <jeremyrcoyle@gmail.com>
# Description: A general framework for the application of cross-validation schemes to particular functions. By allowing arbitrary lists of results, origami accommodates a range of cross-validation applications.
# Depends: R (>= 3.0.0),
# License: GPL-3
# URL: https://tlverse.org/origami
# BugReports: https://github.com/tlverse/origami/issues
# Encoding: UTF-8
# Imports: abind, methods, data.table, assertthat, future, future.apply, listenv
# Suggests: testthat, class, rmarkdown, knitr, stringr, forecast, randomForest
# LazyData: true
# VignetteBuilder: knitr
# RoxygenNote: 7.0.2
# NeedsCompilation: no
# Packaged: 2020-01-16 22:21:08 UTC; nsh
# Author: Jeremy Coyle [aut, cre, cph] (<https://orcid.org/0000-0002-9874-6649>), Nima Hejazi [aut] (<https://orcid.org/0000-0002-7127-2789>), Ivana Malenica [ctb] (<https://orcid.org/0000-0002-7404-8088>), Rachael Phillips [ctb] (<https://orcid.org/0000-0002-8474-591X>)
# Repository: CRAN
# Date/Publication: 2020-01-16 22:40:02 UTC
