appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: X6lZXZlr8YE+DIgMPcLMrejRzrEWP+sPKOHic5rNFj8/7KQsg3sXHxTH4NrIjOmrezISdmQdEqUdQIjbIxlUt6cg1CxE1OlEPGnUBgou5OQm17Z1p8XCUg7W/c/nf+2898SolIjHlnKrG83b2LQ/bZs6Tvk1/3QUcihOttxpGStVk4HEgan8wxOY9E2U+E7ri5cONS/pBpiNoq0eSobDC+mcgO3Zg+Nm8RY1ggzl3DsKMy6D0U02lPxuA/fjd8PqyMhX54S1ufAETe5jM760Nyco+LC4vlmlc/G/I88SRQeH3z1zesxG2izm2kAvKgBUsYTK5bu7QwXbTB49eHekB92UN7A+OWivGN/XaVI9At3OQNnNnWcCVxtUJ5cihFqKfx1Jk17AhYO3JNXqSHKZVjG0X98Gk4XVu0Tbb0XPd9KMOdrCd2gz6j6vWAivw7YgWV8DL1AmKApKiqgnDph/YeRtScBffTwWzvoxgVnOpopL+KVcgkF4eH6POwlO+Oos97Bs6z1RHxtJcUS2f8cz2RUf2UAgHxy4iikv7bvMUFAbGkZvXQqhEu3kcT1e4woxJDUyDcKRCiMTwSNXuBD2U963gZ/ELN8Caw+sS118u8Rymv+CpSl1fFT6hG6HC4Ta+vl2q5/pEX+fqEOXd6qT1Nlcu+RyUFaIuL8KIHZMc2U=}
bot:
  automerge: true
